-- ============================================================================
-- Schéma Oracle - Plateforme de domiciliation bancaire (R06 BCEAO)
-- Contexte réglementaire :
--  - Instruction n°02/07/2025/RFE (Importations - DIM)
--  - Instruction n°03/07/2025/RFE (Exportations - DEX)
-- ============================================================================

-- ============================================================================
-- 1) TABLES DE REFERENCE
-- ============================================================================

CREATE TABLE ROLES (
    ID                  NUMBER(19)      NOT NULL,
    CODE                VARCHAR2(30)    NOT NULL,
    LIBELLE             VARCHAR2(100)   NOT NULL,
    DESCRIPTION         VARCHAR2(500),
    CONSTRAINT PK_ROLES PRIMARY KEY (ID),
    CONSTRAINT UQ_ROLES_CODE UNIQUE (CODE)
);

CREATE TABLE UTILISATEURS (
    ID                  NUMBER(19)       NOT NULL,
    NOM                 VARCHAR2(120)    NOT NULL,
    PRENOM              VARCHAR2(120)    NOT NULL,
    EMAIL               VARCHAR2(190)    NOT NULL,
    LOGIN               VARCHAR2(80)     NOT NULL,
    MOT_DE_PASSE_HASH   VARCHAR2(255)    NOT NULL,
    ROLE_ID             NUMBER(19)       NOT NULL,
    ACTIF               NUMBER(1)        DEFAULT 1 NOT NULL,
    DATE_CREATION       TIMESTAMP        DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_UTILISATEURS PRIMARY KEY (ID),
    CONSTRAINT UQ_UTILISATEURS_EMAIL UNIQUE (EMAIL),
    CONSTRAINT UQ_UTILISATEURS_LOGIN UNIQUE (LOGIN),
    CONSTRAINT FK_UTILISATEURS_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID),
    CONSTRAINT CK_UTILISATEURS_ACTIF CHECK (ACTIF IN (0, 1))
);

CREATE TABLE PARAMETRES (
    ID                  NUMBER(19)       NOT NULL,
    CODE                VARCHAR2(80)     NOT NULL,
    VALEUR              VARCHAR2(500)    NOT NULL,
    DESCRIPTION         VARCHAR2(500),
    MODIFIABLE_ADMIN    NUMBER(1)        DEFAULT 1 NOT NULL,
    CONSTRAINT PK_PARAMETRES PRIMARY KEY (ID),
    CONSTRAINT UQ_PARAMETRES_CODE UNIQUE (CODE),
    CONSTRAINT CK_PARAMETRES_MODIF CHECK (MODIFIABLE_ADMIN IN (0, 1))
);

-- ============================================================================
-- 2) TABLES DOSSIERS (COMMUN, DIM, DEX)
-- ============================================================================

CREATE TABLE DOSSIERS (
    ID                      NUMBER(19)       NOT NULL,
    TYPE_DOSSIER            VARCHAR2(3)      NOT NULL,
    NUMERO_ORDRE            VARCHAR2(60)     NOT NULL,
    DATE_OUVERTURE          DATE             NOT NULL,
    STATUT                  VARCHAR2(40)     NOT NULL,
    OPERATEUR_NOM           VARCHAR2(255)    NOT NULL,
    CODE_STATISTIQUE_NIF    VARCHAR2(80),
    DEVISE                  VARCHAR2(3)      NOT NULL,
    MONTANT_DEVISES         NUMBER(19,2)     NOT NULL,
    CONTRE_VALEUR_FCFA      NUMBER(19,2)     NOT NULL,
    DATE_APUREMENT          DATE,
    UTILISATEUR_CREATEUR_ID NUMBER(19),
    DATE_CREATION           TIMESTAMP        DEFAULT SYSTIMESTAMP NOT NULL,
    DATE_MAJ                TIMESTAMP,
    CONSTRAINT PK_DOSSIERS PRIMARY KEY (ID),
    CONSTRAINT UQ_DOSSIERS_NUM_ORDRE UNIQUE (NUMERO_ORDRE),
    CONSTRAINT FK_DOSSIERS_CREATEUR FOREIGN KEY (UTILISATEUR_CREATEUR_ID) REFERENCES UTILISATEURS (ID),
    CONSTRAINT CK_DOSSIERS_TYPE CHECK (TYPE_DOSSIER IN ('DIM', 'DEX')),
    CONSTRAINT CK_DOSSIERS_STATUT CHECK (
        STATUT IN (
            'INAPTE',
            'INCOMPLET',
            'PRET_OUVERTURE',
            'EN_ATTENTE_OUVERTURE',
            'OUVERT',
            'EN_COURS_EXECUTION',
            'EN_ATTENTE_VALIDATION',
            'VALIDE',
            'REJETE',
            'APURE'
        )
    )
);

CREATE TABLE DOSSIERS_IMPORTATION (
    DOSSIER_ID                  NUMBER(19)       NOT NULL,
    REF_FACTURE_PROFORMA        VARCHAR2(120),
    FOURNISSEUR_NOM             VARCHAR2(255)    NOT NULL,
    FOURNISSEUR_PAYS            VARCHAR2(120)    NOT NULL,
    REF_FACTURE_DEFINITIVE      VARCHAR2(120),
    DATE_FACTURE_DEFINITIVE     DATE,
    CONTRAT_COMMERCIAL_REF      VARCHAR2(120),
    CONSTRAINT PK_DOSSIERS_IMPORTATION PRIMARY KEY (DOSSIER_ID),
    CONSTRAINT FK_DIM_DOSSIER FOREIGN KEY (DOSSIER_ID) REFERENCES DOSSIERS (ID)
);

CREATE TABLE DOSSIERS_EXPORTATION (
    DOSSIER_ID                  NUMBER(19)       NOT NULL,
    ACHETEUR_ETRANGER_NOM       VARCHAR2(255)    NOT NULL,
    PAYS_DESTINATION            VARCHAR2(120)    NOT NULL,
    DATE_EXPEDITION             DATE,
    ENGAGEMENT_CHANGE_REF       VARCHAR2(120),
    CONTRAT_COMMERCIAL_REF      VARCHAR2(120),
    CONSTRAINT PK_DOSSIERS_EXPORTATION PRIMARY KEY (DOSSIER_ID),
    CONSTRAINT FK_DEX_DOSSIER FOREIGN KEY (DOSSIER_ID) REFERENCES DOSSIERS (ID)
);

-- ============================================================================
-- 3) PIECES, CHECKLIST, HISTORIQUE, RELANCES, DATES REGLEMENT/ENCAISSEMENT
-- ============================================================================

CREATE TABLE PIECES_JOINTES (
    ID                  NUMBER(19)       NOT NULL,
    DOSSIER_ID          NUMBER(19)       NOT NULL,
    TYPE_DOSSIER        VARCHAR2(3)      NOT NULL,
    NOM_FICHIER         VARCHAR2(255)    NOT NULL,
    CHEMIN_STOCKAGE     VARCHAR2(500)    NOT NULL,
    TYPE_PIECE          VARCHAR2(100)    NOT NULL,
    DATE_DEPOT          TIMESTAMP        DEFAULT SYSTIMESTAMP NOT NULL,
    DEPOSANT_ID         NUMBER(19)       NOT NULL,
    CONSTRAINT PK_PIECES_JOINTES PRIMARY KEY (ID),
    CONSTRAINT FK_PJ_DOSSIER FOREIGN KEY (DOSSIER_ID) REFERENCES DOSSIERS (ID),
    CONSTRAINT FK_PJ_DEPOSANT FOREIGN KEY (DEPOSANT_ID) REFERENCES UTILISATEURS (ID),
    CONSTRAINT CK_PJ_TYPE_DOSSIER CHECK (TYPE_DOSSIER IN ('DIM', 'DEX'))
);

CREATE TABLE CHECKLIST_ITEMS (
    ID                  NUMBER(19)       NOT NULL,
    DOSSIER_ID          NUMBER(19)       NOT NULL,
    TYPE_DOSSIER        VARCHAR2(3)      NOT NULL,
    CODE_ITEM           VARCHAR2(80)     NOT NULL,
    LIBELLE             VARCHAR2(255)    NOT NULL,
    VALIDE              NUMBER(1)        DEFAULT 0 NOT NULL,
    DATE_VALIDATION     TIMESTAMP,
    VALIDEUR_ID         NUMBER(19),
    CONSTRAINT PK_CHECKLIST_ITEMS PRIMARY KEY (ID),
    CONSTRAINT FK_CHECKLIST_DOSSIER FOREIGN KEY (DOSSIER_ID) REFERENCES DOSSIERS (ID),
    CONSTRAINT FK_CHECKLIST_VALIDEUR FOREIGN KEY (VALIDEUR_ID) REFERENCES UTILISATEURS (ID),
    CONSTRAINT CK_CHECKLIST_TYPE_DOSSIER CHECK (TYPE_DOSSIER IN ('DIM', 'DEX')),
    CONSTRAINT CK_CHECKLIST_VALIDE CHECK (VALIDE IN (0, 1)),
    CONSTRAINT UQ_CHECKLIST_DOSSIER_ITEM UNIQUE (DOSSIER_ID, CODE_ITEM)
);

CREATE TABLE HISTORIQUE_ACTIONS (
    ID                  NUMBER(19)       NOT NULL,
    DOSSIER_ID          NUMBER(19),
    TYPE_DOSSIER        VARCHAR2(3),
    UTILISATEUR_ID      NUMBER(19)       NOT NULL,
    ACTION              VARCHAR2(80)     NOT NULL,
    COMMENTAIRE         VARCHAR2(1000),
    DATE_ACTION         TIMESTAMP        DEFAULT SYSTIMESTAMP NOT NULL,
    DONNEES_AVANT       CLOB,
    DONNEES_APRES       CLOB,
    CONSTRAINT PK_HISTORIQUE_ACTIONS PRIMARY KEY (ID),
    CONSTRAINT FK_HIST_DOSSIER FOREIGN KEY (DOSSIER_ID) REFERENCES DOSSIERS (ID),
    CONSTRAINT FK_HIST_UTILISATEUR FOREIGN KEY (UTILISATEUR_ID) REFERENCES UTILISATEURS (ID),
    CONSTRAINT CK_HIST_TYPE_DOSSIER CHECK (TYPE_DOSSIER IN ('DIM', 'DEX') OR TYPE_DOSSIER IS NULL)
);

CREATE TABLE RELANCES (
    ID                  NUMBER(19)       NOT NULL,
    DOSSIER_ID          NUMBER(19)       NOT NULL,
    TYPE_DOSSIER        VARCHAR2(3)      NOT NULL,
    DATE_RELANCE        TIMESTAMP        DEFAULT SYSTIMESTAMP NOT NULL,
    DESTINATAIRE_EMAIL  VARCHAR2(190)    NOT NULL,
    MOTIF               VARCHAR2(500)    NOT NULL,
    EXPEDITEUR_ID       NUMBER(19)       NOT NULL,
    STATUT_ENVOI        VARCHAR2(30)     NOT NULL,
    TYPE_RELANCE        VARCHAR2(30)     NOT NULL,
    CONSTRAINT PK_RELANCES PRIMARY KEY (ID),
    CONSTRAINT FK_RELANCE_DOSSIER FOREIGN KEY (DOSSIER_ID) REFERENCES DOSSIERS (ID),
    CONSTRAINT FK_RELANCE_EXPEDITEUR FOREIGN KEY (EXPEDITEUR_ID) REFERENCES UTILISATEURS (ID),
    CONSTRAINT CK_RELANCE_TYPE_DOSSIER CHECK (TYPE_DOSSIER IN ('DIM', 'DEX')),
    CONSTRAINT CK_RELANCE_STATUT CHECK (STATUT_ENVOI IN ('EN_ATTENTE', 'ENVOYE', 'ECHEC')),
    CONSTRAINT CK_RELANCE_TYPE CHECK (TYPE_RELANCE IN ('J120_DIM', 'J150_DEX', 'MANUELLE'))
);

CREATE TABLE REGLEMENT_DATES (
    ID                  NUMBER(19)       NOT NULL,
    DOSSIER_ID          NUMBER(19)       NOT NULL,
    TYPE_DOSSIER        VARCHAR2(3)      NOT NULL,
    TYPE_OPERATION      VARCHAR2(20)     NOT NULL,
    DATE_OPERATION      DATE             NOT NULL,
    MONTANT_DEVISES     NUMBER(19,2),
    MONTANT_FCFA        NUMBER(19,2),
    REFERENCE_OPERATION VARCHAR2(120),
    CONSTRAINT PK_REGLEMENT_DATES PRIMARY KEY (ID),
    CONSTRAINT FK_REGLEMENT_DOSSIER FOREIGN KEY (DOSSIER_ID) REFERENCES DOSSIERS (ID),
    CONSTRAINT CK_REGLEMENT_TYPE_DOSSIER CHECK (TYPE_DOSSIER IN ('DIM', 'DEX')),
    CONSTRAINT CK_REGLEMENT_OPERATION CHECK (TYPE_OPERATION IN ('REGLEMENT', 'ENCAISSEMENT'))
);

-- ============================================================================
-- 4) SEQUENCES ORACLE (PK + NUMEROS D'ORDRE)
-- ============================================================================

CREATE SEQUENCE SEQ_ROLES START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_UTILISATEURS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PARAMETRES START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_DOSSIERS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PIECES_JOINTES START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CHECKLIST_ITEMS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_HISTORIQUE_ACTIONS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_RELANCES START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_REGLEMENT_DATES START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Séquences applicatives pour numéros d'ordre (formatage côté backend Spring Boot)
-- DIM : IM + code_banque + code_guichet + année + compteur
-- DEX : EX-B + année + compteur
CREATE SEQUENCE SEQ_NUM_ORDRE_DIM_ANNUEL START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_NUM_ORDRE_DEX_ANNUEL START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- ============================================================================
-- 5) INDEXES (requêtes fréquentes)
-- ============================================================================

CREATE INDEX IDX_DOSSIERS_STATUT ON DOSSIERS (STATUT);
CREATE INDEX IDX_DOSSIERS_DATE_OUVERTURE ON DOSSIERS (DATE_OUVERTURE);
CREATE INDEX IDX_DOSSIERS_NUMERO_ORDRE ON DOSSIERS (NUMERO_ORDRE);
CREATE INDEX IDX_DOSSIERS_OPERATEUR_NOM ON DOSSIERS (OPERATEUR_NOM);

CREATE INDEX IDX_PJ_DOSSIER ON PIECES_JOINTES (DOSSIER_ID);
CREATE INDEX IDX_CHECKLIST_DOSSIER ON CHECKLIST_ITEMS (DOSSIER_ID);
CREATE INDEX IDX_HISTORIQUE_DOSSIER_DATE ON HISTORIQUE_ACTIONS (DOSSIER_ID, DATE_ACTION);
CREATE INDEX IDX_RELANCES_DOSSIER_DATE ON RELANCES (DOSSIER_ID, DATE_RELANCE);
CREATE INDEX IDX_REGLEMENT_DOSSIER_DATE ON REGLEMENT_DATES (DOSSIER_ID, DATE_OPERATION);

-- ============================================================================
-- 6) COMMENTAIRES TABLES ET COLONNES CLES
-- ============================================================================

COMMENT ON TABLE ROLES IS 'Référentiel des rôles applicatifs (agent, chargé, administrateur).';
COMMENT ON TABLE UTILISATEURS IS 'Comptes utilisateurs de la plateforme de domiciliation bancaire.';
COMMENT ON TABLE PARAMETRES IS 'Paramétrage fonctionnel (délais de relance, options métier).';
COMMENT ON TABLE DOSSIERS IS 'Table commune des dossiers de domiciliation (DIM/DEX).';
COMMENT ON TABLE DOSSIERS_IMPORTATION IS 'Données spécifiques aux dossiers d''importation (DIM).';
COMMENT ON TABLE DOSSIERS_EXPORTATION IS 'Données spécifiques aux dossiers d''exportation (DEX).';
COMMENT ON TABLE PIECES_JOINTES IS 'Pièces justificatives déposées pour un dossier DIM/DEX.';
COMMENT ON TABLE CHECKLIST_ITEMS IS 'Checklist de contrôle documentaire et d''exécution du dossier.';
COMMENT ON TABLE HISTORIQUE_ACTIONS IS 'Journal d''audit des actions utilisateur sur les dossiers.';
COMMENT ON TABLE RELANCES IS 'Traçabilité des relances automatiques/manuelles envoyées aux clients.';
COMMENT ON TABLE REGLEMENT_DATES IS 'Historique des dates de règlement (DIM) et encaissement (DEX).';

COMMENT ON COLUMN DOSSIERS.TYPE_DOSSIER IS 'Type de dossier : DIM (importation) ou DEX (exportation).';
COMMENT ON COLUMN DOSSIERS.NUMERO_ORDRE IS 'Numéro d''ordre réglementaire unique du dossier.';
COMMENT ON COLUMN DOSSIERS.OPERATEUR_NOM IS 'Importateur (DIM) ou exportateur (DEX).';
COMMENT ON COLUMN DOSSIERS.STATUT IS 'Statut courant du dossier selon le workflow métier.';
COMMENT ON COLUMN DOSSIERS.CODE_STATISTIQUE_NIF IS 'Code statistique ou NIF de l''opérateur.';
COMMENT ON COLUMN RELANCES.TYPE_RELANCE IS 'Type de relance : J120 DIM, J150 DEX ou manuelle.';
COMMENT ON COLUMN HISTORIQUE_ACTIONS.DONNEES_AVANT IS 'Snapshot JSON avant modification.';
COMMENT ON COLUMN HISTORIQUE_ACTIONS.DONNEES_APRES IS 'Snapshot JSON après modification.';
COMMENT ON COLUMN REGLEMENT_DATES.TYPE_OPERATION IS 'REGLEMENT (DIM) ou ENCAISSEMENT (DEX).';
